// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"vw_comment/internal/biz"
	"vw_comment/internal/conf"
	"vw_comment/internal/data"
	"vw_comment/internal/server"
	"vw_comment/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewMySQL(confData)
	clusterClient := data.NewRedisClusterClient(confData)
	mongoDB := data.NewMongo(confData)
	dataData, cleanup, err := data.NewData(db, clusterClient, mongoDB, logger)
	if err != nil {
		return nil, nil, err
	}
	videoCommentRepo := data.NewVideoCommentRepo(dataData, logger)
	transaction := data.NewTransaction(dataData)
	videoCommentUsecase := biz.NewVideoCommentUsecase(videoCommentRepo, transaction, logger)
	videoCommentService := service.NewVideoCommentService(videoCommentUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, videoCommentService, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
