version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    container_name: mongoDB
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 213103
    volumes:
      - "D:/Environments/Docker datas/MongoDB/logs:/var/log/mongodb"
      - "D:/Environments/Docker datas/MongoDB/data:/data/db"
      - "D:/Environments/Docker datas/MongoDB/config/mongod.conf:/etc/mongod.conf"
      - "D:/Environments/Docker datas/MongoDB/config/mongo-keyfile:/data/mongo-keyfile"
    command: ["/bin/sh", "-c", "chmod 400 /data/mongo-keyfile && mongod --config /etc/mongod.conf --replSet rs0"]
