// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.0
// source: v1/video/video_comment/comment.proto

package video_comment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VideoComment_CommentVideo_FullMethodName      = "/gateway.api.v1.video.comment.VideoComment/CommentVideo"
	VideoComment_GetCommentList_FullMethodName    = "/gateway.api.v1.video.comment.VideoComment/GetCommentList"
	VideoComment_GetCommentReplies_FullMethodName = "/gateway.api.v1.video.comment.VideoComment/GetCommentReplies"
	VideoComment_UpvoteComment_FullMethodName     = "/gateway.api.v1.video.comment.VideoComment/UpvoteComment"
)

// VideoCommentClient is the client API for VideoComment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VideoCommentClient interface {
	CommentVideo(ctx context.Context, in *CommentVideoReq, opts ...grpc.CallOption) (*CommentVideoResp, error)
	GetCommentList(ctx context.Context, in *GetCommentListReq, opts ...grpc.CallOption) (*GetCommentListResp, error)
	GetCommentReplies(ctx context.Context, in *GetCommentRepliesReq, opts ...grpc.CallOption) (*GetCommentRepliesResp, error)
	UpvoteComment(ctx context.Context, in *UpvoteCommentReq, opts ...grpc.CallOption) (*UpvoteCommentResp, error)
}

type videoCommentClient struct {
	cc grpc.ClientConnInterface
}

func NewVideoCommentClient(cc grpc.ClientConnInterface) VideoCommentClient {
	return &videoCommentClient{cc}
}

func (c *videoCommentClient) CommentVideo(ctx context.Context, in *CommentVideoReq, opts ...grpc.CallOption) (*CommentVideoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommentVideoResp)
	err := c.cc.Invoke(ctx, VideoComment_CommentVideo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCommentClient) GetCommentList(ctx context.Context, in *GetCommentListReq, opts ...grpc.CallOption) (*GetCommentListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommentListResp)
	err := c.cc.Invoke(ctx, VideoComment_GetCommentList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCommentClient) GetCommentReplies(ctx context.Context, in *GetCommentRepliesReq, opts ...grpc.CallOption) (*GetCommentRepliesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCommentRepliesResp)
	err := c.cc.Invoke(ctx, VideoComment_GetCommentReplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *videoCommentClient) UpvoteComment(ctx context.Context, in *UpvoteCommentReq, opts ...grpc.CallOption) (*UpvoteCommentResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpvoteCommentResp)
	err := c.cc.Invoke(ctx, VideoComment_UpvoteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VideoCommentServer is the server API for VideoComment service.
// All implementations must embed UnimplementedVideoCommentServer
// for forward compatibility.
type VideoCommentServer interface {
	CommentVideo(context.Context, *CommentVideoReq) (*CommentVideoResp, error)
	GetCommentList(context.Context, *GetCommentListReq) (*GetCommentListResp, error)
	GetCommentReplies(context.Context, *GetCommentRepliesReq) (*GetCommentRepliesResp, error)
	UpvoteComment(context.Context, *UpvoteCommentReq) (*UpvoteCommentResp, error)
	mustEmbedUnimplementedVideoCommentServer()
}

// UnimplementedVideoCommentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVideoCommentServer struct{}

func (UnimplementedVideoCommentServer) CommentVideo(context.Context, *CommentVideoReq) (*CommentVideoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentVideo not implemented")
}
func (UnimplementedVideoCommentServer) GetCommentList(context.Context, *GetCommentListReq) (*GetCommentListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentList not implemented")
}
func (UnimplementedVideoCommentServer) GetCommentReplies(context.Context, *GetCommentRepliesReq) (*GetCommentRepliesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentReplies not implemented")
}
func (UnimplementedVideoCommentServer) UpvoteComment(context.Context, *UpvoteCommentReq) (*UpvoteCommentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpvoteComment not implemented")
}
func (UnimplementedVideoCommentServer) mustEmbedUnimplementedVideoCommentServer() {}
func (UnimplementedVideoCommentServer) testEmbeddedByValue()                      {}

// UnsafeVideoCommentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VideoCommentServer will
// result in compilation errors.
type UnsafeVideoCommentServer interface {
	mustEmbedUnimplementedVideoCommentServer()
}

func RegisterVideoCommentServer(s grpc.ServiceRegistrar, srv VideoCommentServer) {
	// If the following call pancis, it indicates UnimplementedVideoCommentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VideoComment_ServiceDesc, srv)
}

func _VideoComment_CommentVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentVideoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCommentServer).CommentVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoComment_CommentVideo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCommentServer).CommentVideo(ctx, req.(*CommentVideoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoComment_GetCommentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCommentServer).GetCommentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoComment_GetCommentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCommentServer).GetCommentList(ctx, req.(*GetCommentListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoComment_GetCommentReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommentRepliesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCommentServer).GetCommentReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoComment_GetCommentReplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCommentServer).GetCommentReplies(ctx, req.(*GetCommentRepliesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _VideoComment_UpvoteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpvoteCommentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VideoCommentServer).UpvoteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VideoComment_UpvoteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VideoCommentServer).UpvoteComment(ctx, req.(*UpvoteCommentReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VideoComment_ServiceDesc is the grpc.ServiceDesc for VideoComment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VideoComment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.api.v1.video.comment.VideoComment",
	HandlerType: (*VideoCommentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommentVideo",
			Handler:    _VideoComment_CommentVideo_Handler,
		},
		{
			MethodName: "GetCommentList",
			Handler:    _VideoComment_GetCommentList_Handler,
		},
		{
			MethodName: "GetCommentReplies",
			Handler:    _VideoComment_GetCommentReplies_Handler,
		},
		{
			MethodName: "UpvoteComment",
			Handler:    _VideoComment_UpvoteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/video/video_comment/comment.proto",
}
