server:
  http:
    addr: 0.0.0.0:8001
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 10s
log:
  stdout: true  # control output log to stdout
  path: ./log/
  max_size: 256
  max_age: 7
  max_count: 5
registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http
trace:
  endpoint: http://127.0.0.1:14268/api/traces