server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s
log:
  stdout: true  # control output log to stdout
  path: ./log/
  max_size: 256
  max_age: 7
  max_count: 5
data:
  redis_cluster:
    host: 192.168.17.128
    port: ['7000','7001','7002','7003','7004','7005']
    password: F095PfRdmuw5efTZJ2jf
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
    pool_timeout: 4s
    max_retries: 3
    min_idle_conns: 10
jwt:
  secret: Kth1utMBj4jXXVUgz5NtH8SGBnBLMYz
  access_token_expiration: 2                    #2 hours
  refresh_token_expiration: 15                  #15 days
email:
  smtp_host: smtp.qq.com
  smtp_port: 465
  smtp_username: 1010642166@qq.com
  smtp_password: exwxhwxuqwljbfdc
  smtp_servername: smtp.qq.com
registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http
trace:
  endpoint: http://127.0.0.1:14268/api/traces

dtm:
  dtm_config:
    driver: 'dtm-driver-kratos' # name of the driver to handle register/discover
    target: 'consul://127.0.0.1:8500/dtmservice' # register dtm server to this url
    endpoint: 'grpc://localhost:36790'

service:
  user:
    endpoint: discovery:///videoweb.user.service
  video:
    endpoint: discovery:///videoweb.video.service