server:
  http:
    addr: 0.0.0.0:8001
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 10s
log:
  stdout: true  # control output log to stdout
  path: ./log/
  max_size: 256
  max_age: 7
  max_count: 5
registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http
trace:
  endpoint: http://127.0.0.1:14268/api/traces

dtm:
  driver: 'dtm-driver-kratos' # name of the driver to handle register/discover
  target: 'consul://127.0.0.1:8500/dtmservice' # register dtm server to this url
  endpoint: 'grpc://localhost:36790'

service:
  user:
    endpoint: discovery:///videoweb.user.service
  video:
    endpoint: discovery:///videoweb.video.service