// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.0
// source: v1/user/userinfo/userinfo.proto

package infov1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Userinfo_Userinfo_FullMethodName            = "/gateway.api.v1.user.userinfo.Userinfo/Userinfo"
	Userinfo_ModifyEmail_FullMethodName         = "/gateway.api.v1.user.userinfo.Userinfo/ModifyEmail"
	Userinfo_ModifyPassword_FullMethodName      = "/gateway.api.v1.user.userinfo.Userinfo/ModifyPassword"
	Userinfo_ModifyUserSignature_FullMethodName = "/gateway.api.v1.user.userinfo.Userinfo/ModifyUserSignature"
	Userinfo_ForgetPassword_FullMethodName      = "/gateway.api.v1.user.userinfo.Userinfo/ForgetPassword"
	Userinfo_ModifyUsername_FullMethodName      = "/gateway.api.v1.user.userinfo.Userinfo/ModifyUsername"
)

// UserinfoClient is the client API for Userinfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserinfoClient interface {
	Userinfo(ctx context.Context, in *UserinfoReq, opts ...grpc.CallOption) (*UserinfoResp, error)
	ModifyEmail(ctx context.Context, in *ModifyEmailReq, opts ...grpc.CallOption) (*ModifyEmailResp, error)
	ModifyPassword(ctx context.Context, in *ModifyPasswordReq, opts ...grpc.CallOption) (*ModifyPasswordResp, error)
	ModifyUserSignature(ctx context.Context, in *ModifySignatureReq, opts ...grpc.CallOption) (*ModifySignatureResp, error)
	ForgetPassword(ctx context.Context, in *ForgetPasswordReq, opts ...grpc.CallOption) (*ForgetPasswordResp, error)
	ModifyUsername(ctx context.Context, in *ModifyUsernameReq, opts ...grpc.CallOption) (*ModifyUsernameResp, error)
}

type userinfoClient struct {
	cc grpc.ClientConnInterface
}

func NewUserinfoClient(cc grpc.ClientConnInterface) UserinfoClient {
	return &userinfoClient{cc}
}

func (c *userinfoClient) Userinfo(ctx context.Context, in *UserinfoReq, opts ...grpc.CallOption) (*UserinfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserinfoResp)
	err := c.cc.Invoke(ctx, Userinfo_Userinfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userinfoClient) ModifyEmail(ctx context.Context, in *ModifyEmailReq, opts ...grpc.CallOption) (*ModifyEmailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyEmailResp)
	err := c.cc.Invoke(ctx, Userinfo_ModifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userinfoClient) ModifyPassword(ctx context.Context, in *ModifyPasswordReq, opts ...grpc.CallOption) (*ModifyPasswordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyPasswordResp)
	err := c.cc.Invoke(ctx, Userinfo_ModifyPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userinfoClient) ModifyUserSignature(ctx context.Context, in *ModifySignatureReq, opts ...grpc.CallOption) (*ModifySignatureResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifySignatureResp)
	err := c.cc.Invoke(ctx, Userinfo_ModifyUserSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userinfoClient) ForgetPassword(ctx context.Context, in *ForgetPasswordReq, opts ...grpc.CallOption) (*ForgetPasswordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetPasswordResp)
	err := c.cc.Invoke(ctx, Userinfo_ForgetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userinfoClient) ModifyUsername(ctx context.Context, in *ModifyUsernameReq, opts ...grpc.CallOption) (*ModifyUsernameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyUsernameResp)
	err := c.cc.Invoke(ctx, Userinfo_ModifyUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserinfoServer is the server API for Userinfo service.
// All implementations must embed UnimplementedUserinfoServer
// for forward compatibility.
type UserinfoServer interface {
	Userinfo(context.Context, *UserinfoReq) (*UserinfoResp, error)
	ModifyEmail(context.Context, *ModifyEmailReq) (*ModifyEmailResp, error)
	ModifyPassword(context.Context, *ModifyPasswordReq) (*ModifyPasswordResp, error)
	ModifyUserSignature(context.Context, *ModifySignatureReq) (*ModifySignatureResp, error)
	ForgetPassword(context.Context, *ForgetPasswordReq) (*ForgetPasswordResp, error)
	ModifyUsername(context.Context, *ModifyUsernameReq) (*ModifyUsernameResp, error)
	mustEmbedUnimplementedUserinfoServer()
}

// UnimplementedUserinfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserinfoServer struct{}

func (UnimplementedUserinfoServer) Userinfo(context.Context, *UserinfoReq) (*UserinfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Userinfo not implemented")
}
func (UnimplementedUserinfoServer) ModifyEmail(context.Context, *ModifyEmailReq) (*ModifyEmailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyEmail not implemented")
}
func (UnimplementedUserinfoServer) ModifyPassword(context.Context, *ModifyPasswordReq) (*ModifyPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyPassword not implemented")
}
func (UnimplementedUserinfoServer) ModifyUserSignature(context.Context, *ModifySignatureReq) (*ModifySignatureResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyUserSignature not implemented")
}
func (UnimplementedUserinfoServer) ForgetPassword(context.Context, *ForgetPasswordReq) (*ForgetPasswordResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ForgetPassword not implemented")
}
func (UnimplementedUserinfoServer) ModifyUsername(context.Context, *ModifyUsernameReq) (*ModifyUsernameResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyUsername not implemented")
}
func (UnimplementedUserinfoServer) mustEmbedUnimplementedUserinfoServer() {}
func (UnimplementedUserinfoServer) testEmbeddedByValue()                  {}

// UnsafeUserinfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserinfoServer will
// result in compilation errors.
type UnsafeUserinfoServer interface {
	mustEmbedUnimplementedUserinfoServer()
}

func RegisterUserinfoServer(s grpc.ServiceRegistrar, srv UserinfoServer) {
	// If the following call pancis, it indicates UnimplementedUserinfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Userinfo_ServiceDesc, srv)
}

func _Userinfo_Userinfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserinfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserinfoServer).Userinfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userinfo_Userinfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserinfoServer).Userinfo(ctx, req.(*UserinfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userinfo_ModifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyEmailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserinfoServer).ModifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userinfo_ModifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserinfoServer).ModifyEmail(ctx, req.(*ModifyEmailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userinfo_ModifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserinfoServer).ModifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userinfo_ModifyPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserinfoServer).ModifyPassword(ctx, req.(*ModifyPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userinfo_ModifyUserSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifySignatureReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserinfoServer).ModifyUserSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userinfo_ModifyUserSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserinfoServer).ModifyUserSignature(ctx, req.(*ModifySignatureReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userinfo_ForgetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserinfoServer).ForgetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userinfo_ForgetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserinfoServer).ForgetPassword(ctx, req.(*ForgetPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Userinfo_ModifyUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyUsernameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserinfoServer).ModifyUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Userinfo_ModifyUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserinfoServer).ModifyUsername(ctx, req.(*ModifyUsernameReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Userinfo_ServiceDesc is the grpc.ServiceDesc for Userinfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Userinfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.api.v1.user.userinfo.Userinfo",
	HandlerType: (*UserinfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Userinfo",
			Handler:    _Userinfo_Userinfo_Handler,
		},
		{
			MethodName: "ModifyEmail",
			Handler:    _Userinfo_ModifyEmail_Handler,
		},
		{
			MethodName: "ModifyPassword",
			Handler:    _Userinfo_ModifyPassword_Handler,
		},
		{
			MethodName: "ModifyUserSignature",
			Handler:    _Userinfo_ModifyUserSignature_Handler,
		},
		{
			MethodName: "ForgetPassword",
			Handler:    _Userinfo_ForgetPassword_Handler,
		},
		{
			MethodName: "ModifyUsername",
			Handler:    _Userinfo_ModifyUsername_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/user/userinfo/userinfo.proto",
}
