// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: v1/follow/user_follow.proto

package followv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FollowUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowerUserId int64 `protobuf:"varint,2,opt,name=follower_user_id,json=followerUserId,proto3" json:"follower_user_id,omitempty"`
	FollowListId   int64 `protobuf:"varint,3,opt,name=follow_list_id,json=followListId,proto3" json:"follow_list_id,omitempty"`
}

func (x *FollowUserReq) Reset() {
	*x = FollowUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_follow_user_follow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserReq) ProtoMessage() {}

func (x *FollowUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_user_follow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserReq.ProtoReflect.Descriptor instead.
func (*FollowUserReq) Descriptor() ([]byte, []int) {
	return file_v1_follow_user_follow_proto_rawDescGZIP(), []int{0}
}

func (x *FollowUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowUserReq) GetFollowerUserId() int64 {
	if x != nil {
		return x.FollowerUserId
	}
	return 0
}

func (x *FollowUserReq) GetFollowListId() int64 {
	if x != nil {
		return x.FollowListId
	}
	return 0
}

type FollowUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *FollowUserResp) Reset() {
	*x = FollowUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_follow_user_follow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FollowUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserResp) ProtoMessage() {}

func (x *FollowUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_user_follow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserResp.ProtoReflect.Descriptor instead.
func (*FollowUserResp) Descriptor() ([]byte, []int) {
	return file_v1_follow_user_follow_proto_rawDescGZIP(), []int{1}
}

func (x *FollowUserResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *FollowUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnfollowUserReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId         int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FolloweeUserId int64 `protobuf:"varint,2,opt,name=followee_user_id,json=followeeUserId,proto3" json:"followee_user_id,omitempty"`
}

func (x *UnfollowUserReq) Reset() {
	*x = UnfollowUserReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_follow_user_follow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnfollowUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserReq) ProtoMessage() {}

func (x *UnfollowUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_user_follow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserReq.ProtoReflect.Descriptor instead.
func (*UnfollowUserReq) Descriptor() ([]byte, []int) {
	return file_v1_follow_user_follow_proto_rawDescGZIP(), []int{2}
}

func (x *UnfollowUserReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnfollowUserReq) GetFolloweeUserId() int64 {
	if x != nil {
		return x.FolloweeUserId
	}
	return 0
}

type UnfollowUserResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode int32  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message    string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UnfollowUserResp) Reset() {
	*x = UnfollowUserResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_follow_user_follow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnfollowUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserResp) ProtoMessage() {}

func (x *UnfollowUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_user_follow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserResp.ProtoReflect.Descriptor instead.
func (*UnfollowUserResp) Descriptor() ([]byte, []int) {
	return file_v1_follow_user_follow_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowUserResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UnfollowUserResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetFolloweesInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowListId int64 `protobuf:"varint,2,opt,name=follow_list_id,json=followListId,proto3" json:"follow_list_id,omitempty"`
	PageNum      int32 `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize     int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *GetFolloweesInfoReq) Reset() {
	*x = GetFolloweesInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_follow_user_follow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFolloweesInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolloweesInfoReq) ProtoMessage() {}

func (x *GetFolloweesInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_user_follow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolloweesInfoReq.ProtoReflect.Descriptor instead.
func (*GetFolloweesInfoReq) Descriptor() ([]byte, []int) {
	return file_v1_follow_user_follow_proto_rawDescGZIP(), []int{4}
}

func (x *GetFolloweesInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetFolloweesInfoReq) GetFollowListId() int64 {
	if x != nil {
		return x.FollowListId
	}
	return 0
}

func (x *GetFolloweesInfoReq) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *GetFolloweesInfoReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetFolloweesInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StatusCode    int32                               `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Message       string                              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	FolloweesInfo []*GetFolloweesInfoResp_UserSummary `protobuf:"bytes,3,rep,name=followees_info,json=followeesInfo,proto3" json:"followees_info,omitempty"`
}

func (x *GetFolloweesInfoResp) Reset() {
	*x = GetFolloweesInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_follow_user_follow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFolloweesInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolloweesInfoResp) ProtoMessage() {}

func (x *GetFolloweesInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_user_follow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolloweesInfoResp.ProtoReflect.Descriptor instead.
func (*GetFolloweesInfoResp) Descriptor() ([]byte, []int) {
	return file_v1_follow_user_follow_proto_rawDescGZIP(), []int{5}
}

func (x *GetFolloweesInfoResp) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetFolloweesInfoResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetFolloweesInfoResp) GetFolloweesInfo() []*GetFolloweesInfoResp_UserSummary {
	if x != nil {
		return x.FolloweesInfo
	}
	return nil
}

type GetFolloweesInfoResp_UserSummary struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username   string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email      string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Signature  string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	AvatarPath string                 `protobuf:"bytes,4,opt,name=avatar_path,json=avatarPath,proto3" json:"avatar_path,omitempty"`
	Gender     int32                  `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
}

func (x *GetFolloweesInfoResp_UserSummary) Reset() {
	*x = GetFolloweesInfoResp_UserSummary{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_follow_user_follow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFolloweesInfoResp_UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFolloweesInfoResp_UserSummary) ProtoMessage() {}

func (x *GetFolloweesInfoResp_UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_v1_follow_user_follow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFolloweesInfoResp_UserSummary.ProtoReflect.Descriptor instead.
func (*GetFolloweesInfoResp_UserSummary) Descriptor() ([]byte, []int) {
	return file_v1_follow_user_follow_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetFolloweesInfoResp_UserSummary) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetFolloweesInfoResp_UserSummary) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetFolloweesInfoResp_UserSummary) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *GetFolloweesInfoResp_UserSummary) GetAvatarPath() string {
	if x != nil {
		return x.AvatarPath
	}
	return ""
}

func (x *GetFolloweesInfoResp_UserSummary) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *GetFolloweesInfoResp_UserSummary) GetBirthday() *timestamppb.Timestamp {
	if x != nil {
		return x.Birthday
	}
	return nil
}

var File_v1_follow_user_follow_proto protoreflect.FileDescriptor

var file_v1_follow_user_follow_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x76, 0x31, 0x2f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x78,
	0x0a, 0x0d, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x22, 0x4b, 0x0a, 0x0e, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x54, 0x0a, 0x0f, 0x55, 0x6e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x28, 0x0a, 0x10, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x65, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x10, 0x55,
	0x6e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x8c, 0x01, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x66,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x4c, 0x69, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xfb, 0x02, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x57, 0x0a,
	0x0e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x65, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x52, 0x0d, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0xce, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x75, 0x6d, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x36, 0x0a, 0x08, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x62,
	0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x79, 0x32, 0x8d, 0x02, 0x0a, 0x06, 0x46, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x12, 0x4d, 0x0a, 0x0a, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f,
	0x77, 0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x2e, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x53, 0x0a, 0x0c, 0x55, 0x6e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x1f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x6f, 0x6c, 0x6c,
	0x6f, 0x77, 0x2e, 0x55, 0x6e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x2e, 0x55, 0x6e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x2e, 0x47, 0x65, 0x74, 0x46,
	0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a,
	0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x65, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x20, 0x5a, 0x1e, 0x76, 0x77, 0x5f, 0x75, 0x73,
	0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77,
	0x3b, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_v1_follow_user_follow_proto_rawDescOnce sync.Once
	file_v1_follow_user_follow_proto_rawDescData = file_v1_follow_user_follow_proto_rawDesc
)

func file_v1_follow_user_follow_proto_rawDescGZIP() []byte {
	file_v1_follow_user_follow_proto_rawDescOnce.Do(func() {
		file_v1_follow_user_follow_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_follow_user_follow_proto_rawDescData)
	})
	return file_v1_follow_user_follow_proto_rawDescData
}

var file_v1_follow_user_follow_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_v1_follow_user_follow_proto_goTypes = []any{
	(*FollowUserReq)(nil),                    // 0: userbiz.v1.follow.FollowUserReq
	(*FollowUserResp)(nil),                   // 1: userbiz.v1.follow.FollowUserResp
	(*UnfollowUserReq)(nil),                  // 2: userbiz.v1.follow.UnfollowUserReq
	(*UnfollowUserResp)(nil),                 // 3: userbiz.v1.follow.UnfollowUserResp
	(*GetFolloweesInfoReq)(nil),              // 4: userbiz.v1.follow.GetFolloweesInfoReq
	(*GetFolloweesInfoResp)(nil),             // 5: userbiz.v1.follow.GetFolloweesInfoResp
	(*GetFolloweesInfoResp_UserSummary)(nil), // 6: userbiz.v1.follow.GetFolloweesInfoResp.UserSummary
	(*timestamppb.Timestamp)(nil),            // 7: google.protobuf.Timestamp
}
var file_v1_follow_user_follow_proto_depIdxs = []int32{
	6, // 0: userbiz.v1.follow.GetFolloweesInfoResp.followees_info:type_name -> userbiz.v1.follow.GetFolloweesInfoResp.UserSummary
	7, // 1: userbiz.v1.follow.GetFolloweesInfoResp.UserSummary.birthday:type_name -> google.protobuf.Timestamp
	0, // 2: userbiz.v1.follow.Follow.FollowUser:input_type -> userbiz.v1.follow.FollowUserReq
	2, // 3: userbiz.v1.follow.Follow.UnfollowUser:input_type -> userbiz.v1.follow.UnfollowUserReq
	4, // 4: userbiz.v1.follow.Follow.GetFolloweesInfo:input_type -> userbiz.v1.follow.GetFolloweesInfoReq
	1, // 5: userbiz.v1.follow.Follow.FollowUser:output_type -> userbiz.v1.follow.FollowUserResp
	3, // 6: userbiz.v1.follow.Follow.UnfollowUser:output_type -> userbiz.v1.follow.UnfollowUserResp
	5, // 7: userbiz.v1.follow.Follow.GetFolloweesInfo:output_type -> userbiz.v1.follow.GetFolloweesInfoResp
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_follow_user_follow_proto_init() }
func file_v1_follow_user_follow_proto_init() {
	if File_v1_follow_user_follow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_follow_user_follow_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FollowUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_follow_user_follow_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FollowUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_follow_user_follow_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UnfollowUserReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_follow_user_follow_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UnfollowUserResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_follow_user_follow_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetFolloweesInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_follow_user_follow_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetFolloweesInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_follow_user_follow_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetFolloweesInfoResp_UserSummary); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_follow_user_follow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_follow_user_follow_proto_goTypes,
		DependencyIndexes: file_v1_follow_user_follow_proto_depIdxs,
		MessageInfos:      file_v1_follow_user_follow_proto_msgTypes,
	}.Build()
	File_v1_follow_user_follow_proto = out.File
	file_v1_follow_user_follow_proto_rawDesc = nil
	file_v1_follow_user_follow_proto_goTypes = nil
	file_v1_follow_user_follow_proto_depIdxs = nil
}
