// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVideoClass = "video_class"

// VideoClass 视频分类表，存储每个视频的类别信息
type VideoClass struct {
	VideoID int64  `gorm:"column:video_id;type:bigint;primaryKey;comment:视频id，" json:"video_id"` // 视频id，
	Class   string `gorm:"column:class;type:varchar(20);primaryKey;comment:视频分类" json:"class"`   // 视频分类
}

// TableName VideoClass's table name
func (*VideoClass) TableName() string {
	return TableNameVideoClass
}
