// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: v1/userfile/user_file.proto

package filev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadAvatarReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*UploadAvatarReq_FileName
	//	*UploadAvatarReq_FileContent
	Data isUploadAvatarReq_Data `protobuf_oneof:"data"`
}

func (x *UploadAvatarReq) Reset() {
	*x = UploadAvatarReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_userfile_user_file_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadAvatarReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarReq) ProtoMessage() {}

func (x *UploadAvatarReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_userfile_user_file_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarReq.ProtoReflect.Descriptor instead.
func (*UploadAvatarReq) Descriptor() ([]byte, []int) {
	return file_v1_userfile_user_file_proto_rawDescGZIP(), []int{0}
}

func (m *UploadAvatarReq) GetData() isUploadAvatarReq_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UploadAvatarReq) GetFileName() string {
	if x, ok := x.GetData().(*UploadAvatarReq_FileName); ok {
		return x.FileName
	}
	return ""
}

func (x *UploadAvatarReq) GetFileContent() []byte {
	if x, ok := x.GetData().(*UploadAvatarReq_FileContent); ok {
		return x.FileContent
	}
	return nil
}

type isUploadAvatarReq_Data interface {
	isUploadAvatarReq_Data()
}

type UploadAvatarReq_FileName struct {
	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3,oneof"`
}

type UploadAvatarReq_FileContent struct {
	FileContent []byte `protobuf:"bytes,2,opt,name=file_content,json=fileContent,proto3,oneof"`
}

func (*UploadAvatarReq_FileName) isUploadAvatarReq_Data() {}

func (*UploadAvatarReq_FileContent) isUploadAvatarReq_Data() {}

type UploadAvatarResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FilePath string `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
}

func (x *UploadAvatarResp) Reset() {
	*x = UploadAvatarResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_userfile_user_file_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadAvatarResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAvatarResp) ProtoMessage() {}

func (x *UploadAvatarResp) ProtoReflect() protoreflect.Message {
	mi := &file_v1_userfile_user_file_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAvatarResp.ProtoReflect.Descriptor instead.
func (*UploadAvatarResp) Descriptor() ([]byte, []int) {
	return file_v1_userfile_user_file_proto_rawDescGZIP(), []int{1}
}

func (x *UploadAvatarResp) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

var File_v1_userfile_user_file_proto protoreflect.FileDescriptor

var file_v1_userfile_user_file_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x76, 0x31, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x5d, 0x0a, 0x0f, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1d,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x00, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a,
	0x0c, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2f, 0x0a, 0x10, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x32, 0x60, 0x0a, 0x0b, 0x46,
	0x69, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1d, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x28, 0x01, 0x42, 0x20, 0x5a,
	0x1e, 0x76, 0x77, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x65, 0x3b, 0x66, 0x69, 0x6c, 0x65, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_userfile_user_file_proto_rawDescOnce sync.Once
	file_v1_userfile_user_file_proto_rawDescData = file_v1_userfile_user_file_proto_rawDesc
)

func file_v1_userfile_user_file_proto_rawDescGZIP() []byte {
	file_v1_userfile_user_file_proto_rawDescOnce.Do(func() {
		file_v1_userfile_user_file_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_userfile_user_file_proto_rawDescData)
	})
	return file_v1_userfile_user_file_proto_rawDescData
}

var file_v1_userfile_user_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_userfile_user_file_proto_goTypes = []any{
	(*UploadAvatarReq)(nil),  // 0: user.v1.file.UploadAvatarReq
	(*UploadAvatarResp)(nil), // 1: user.v1.file.UploadAvatarResp
}
var file_v1_userfile_user_file_proto_depIdxs = []int32{
	0, // 0: user.v1.file.FileService.UploadAvatar:input_type -> user.v1.file.UploadAvatarReq
	1, // 1: user.v1.file.FileService.UploadAvatar:output_type -> user.v1.file.UploadAvatarResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_userfile_user_file_proto_init() }
func file_v1_userfile_user_file_proto_init() {
	if File_v1_userfile_user_file_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_userfile_user_file_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UploadAvatarReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_userfile_user_file_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UploadAvatarResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_userfile_user_file_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadAvatarReq_FileName)(nil),
		(*UploadAvatarReq_FileContent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_userfile_user_file_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_userfile_user_file_proto_goTypes,
		DependencyIndexes: file_v1_userfile_user_file_proto_depIdxs,
		MessageInfos:      file_v1_userfile_user_file_proto_msgTypes,
	}.Build()
	File_v1_userfile_user_file_proto = out.File
	file_v1_userfile_user_file_proto_rawDesc = nil
	file_v1_userfile_user_file_proto_goTypes = nil
	file_v1_userfile_user_file_proto_depIdxs = nil
}
