server:
  http:
    addr: 0.0.0.0:8003
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9003
    timeout: 10s
log:
  stdout: true  # control output log to stdout
  path: ./log/
  max_size: 256
  max_age: 7
  max_count: 5
data:
  mysql:
    log_level: 4  # 1: silent, 2: error, 3: warn, 4: info, 5: debug
    host: 127.0.0.1
    port: '3306'
    user: root
    password: <your mysql_password>
    database: vw_comment
    max_idle: 10
    max_open: 100
  redis:
    host: 127.0.0.1
    port: '6379'
    db: 1
    password: <your redis_password>
    dial_timeout: 1s
    read_timeout: 1s
    write_timeout: 1s
  mongo:
    host: 127.0.0.1
    port: '27017'
    db: vw_user
    password: <your mongo_password>
    max_open_conns: 100
    conn_timeout: 1s
registry:
  consul:
    address: 127.0.0.1:8500
    scheme: http