// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"vw_gateway/internal/biz/userbiz"
	"vw_gateway/internal/conf"
	"vw_gateway/internal/data/userdata"
	"vw_gateway/internal/pkg/captcha"
	"vw_gateway/internal/pkg/middlewares/auth"
	"vw_gateway/internal/server"
	"vw_gateway/internal/service/user_service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, registry *conf.Registry, jwt *conf.JWT, email *conf.Email, trace *conf.Trace, service *conf.Service, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, logger)
	discovery := userdata.NewDiscovery(registry)
	identityClient := userdata.NewUserIdentityClient(discovery, service)
	userinfoClient := userdata.NewUserinfoClient(discovery, service)
	captchaClient := userdata.NewCaptchaClient(discovery, service)
	fileServiceClient := userdata.NewFileClient(discovery, service)
	favoriteClient := userdata.NewFavoritesClient(discovery, service)
	followClient := userdata.NewFollowClient(discovery, service)
	clusterClient := userdata.NewRedisClusterClient(data)
	userdataData, cleanup, err := userdata.NewData(logger, identityClient, userinfoClient, captchaClient, fileServiceClient, favoriteClient, followClient, clusterClient)
	if err != nil {
		return nil, nil, err
	}
	captchaRepo := userdata.NewCaptchaRepo(logger, userdataData)
	captchaEmail := captcha.NewEmail(email, logger)
	captchaUsecase := userbiz.NewCaptchaUsecase(logger, captchaRepo, captchaEmail)
	captchaService := user.NewCaptchaService(logger, captchaUsecase)
	userFileRepo := userdata.NewUserFileRepo(userdataData, logger)
	userFileUsecase := userbiz.NewUserFileUsecase(userFileRepo, logger)
	userFileService := user.NewUserFileService(userFileUsecase, logger)
	userIdentityRepo := userdata.NewUserIdentityRepo(userdataData, logger)
	jwtAuth := auth.NewJWTAuth(jwt)
	userIdentityUsecase := userbiz.NewUserIdentityUsecase(userIdentityRepo, jwtAuth, logger)
	userIdentityService := user.NewUserIdentityService(userIdentityUsecase, logger)
	followRepo := userdata.NewFollowRepo(userdataData, logger)
	followUsecase := userbiz.NewFollowUsecase(followRepo, logger)
	followService := user.NewFollowService(logger, followUsecase)
	userinfoRepo := userdata.NewUserInfoRepo(userdataData, logger)
	userinfoUsecase := userbiz.NewUserinfoUsecase(userinfoRepo, logger)
	userinfoService := user.NewUserinfoService(userinfoUsecase, logger)
	favoritesRepo := userdata.NewFavoritesRepo(userdataData, favoriteClient, logger)
	favoritesUsecase := userbiz.NewFavoritesUsecase(favoritesRepo, logger)
	favoritesService := user.NewFavoritesService(favoritesUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, jwt, captchaService, userFileService, userIdentityService, followService, clusterClient, userinfoService, favoritesService, logger)
	registrar := userdata.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
